### ISSUE TITLE
Recent bug in API

### ISSUE THREAD

**Issue by gondhijagapathi** [dasshubham762/atomberg-integration#24]
## System Information

version | core-2024.10.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 5.15.0-124-generic
arch | x86_64
timezone | Asia/Calcutta
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4980
Installed Version | 2.0.1
Stage | running
Available Repositories | 1448
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 14
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | October 13, 2024 at 2:42 AM
-- | --
current_recorder_run | October 23, 2024 at 1:32 PM
estimated_db_size | 27.24 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Adding new Atomberg / operating current added fans, is no longer available because of atomberg api issue,

I already mailed atomberg about this issue, here is the summary of the email 

`Hi Team,

recently we are getting errors in get_device_state api, can you please fix it :) 

{
  "errorType": "TypeError",
  "errorMessage": "Cannot read properties of undefined (reading '_seconds')",
  "trace": [
    "TypeError: Cannot read properties of undefined (reading '_seconds')",
    "    at exports.handler (/var/task/get_device_state.js:43:46)",
    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
  ]
}`

can we please print proper errors when this happens? like what api failed etc

### Reproduction steps

1. Add new atomberg intigration
2.
3.
...

### Debug logs

```text
2024-10-23 08:18:46.959 ERROR (MainThread) [custom_components.atomberg.config_flow] Unexpected exception

Traceback (most recent call last):

  File "/config/custom_components/atomberg/config_flow.py", line 54, in async_step_user

    info = await validate_input(self.hass, user_input)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/atomberg/config_flow.py", line 34, in validate_input

    if not await api.test_connection():

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/atomberg/api.py", line 32, in test_connection

    if not await self.async_sync_list_of_devices():

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/atomberg/api.py", line 120, in async_sync_list_of_devices

    states = await self.async_get_device_state()

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/config/custom_components/atomberg/api.py", line 143, in async_get_device_state

    if data["status"] == "Success":

       ~~~~^^^^^^^^^^

KeyError: 'status'
```

**Comment by gondhijagapathi** [comment]
keeping this issue open, so people who are using this can be aware of the issue

**Comment by gondhijagapathi** [comment]
lol they fixed it in half hour after I emailed.
